version: '3.1'
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - local-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  local-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
